### ISSUE TITLE
Parse fusionVersion from location with tar.gz

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/libseqera#14]
Currently, we parse fusionVersion from a location with .json file.
https://github.com/seqeralabs/libseqera/blob/6a7efe04f47717acbdfae2db989d6e943fa4ece7/wave-api/src/test/groovy/io/seqera/wave/api/FusionVersionTest.groovy#L35

but as mentioned in this comment https://github.com/seqeralabs/wave/pull/393#issuecomment-1943589365
location is `https://fusionfs.seqera.io/releases/pkg/2/2/8/fusion-amd64.tar.gz`

we are paring the location https://github.com/seqeralabs/libseqera/blob/88d7fac231b0c0c18a9a39553eff0e2ccc45f5b5/wave-api/src/main/java/io/seqera/wave/api/ContainerConfig.java#L99

So another parser is needed to parse version from this URL

**Comment by pditommaso** [comment]
Not understanding what's the question

**Comment by munishchouhan** [comment]
now i got the clarification that we need a new regex to parse the correct version
I was trying to clarify, if https://fusionfs.seqera.io/releases/pkg/2/2/8/fusion-amd64.tar.gz is correct location or not

But now I know that this is the correct. location and I have created a pr
